### ISSUE TITLE
Change the category of the wazuh-security-dashboards-plugin

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh-security-dashboards-plugin#23]
**Describe the enhancement**

We want to rename the app category that is registered and displayed in the UI, the security application.

Proposed solution: remove the branding name.

![image](https://github.com/wazuh/wazuh-security-dashboards-plugin/assets/34042064/5d48e4ae-8bd7-4a52-b09d-ad7118429378)

**Comment by AlexRuiz7** [comment]
Out of scope
