### ISSUE TITLE
Compatibility with Security Dashboards Plugin 2.10.0.0

### ISSUE THREAD

**Issue by yenienserrano** [wazuh/wazuh-security-dashboards-plugin#28]
We need to ensure the UI compatibility with the next version of Security Dashboards Plugin vX.X.
This update is still being discussed, but we need to be aware of potential issues.

For that, we need to:

- [x] Review Security Dashboards Plugin latest stable changelog. 
- [x] Identify improvements and potential impact on the UI.
- [x] Create new tracking and development branches.
- [x] Develop a testing environment to verify our components would work under this new build.

**Comment by AlexRuiz7** [comment]
Supersued by #31
