### ISSUE TITLE
Compatibility with new OpenSearch's security-dashboards-plugin 2.11.0

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-security-dashboards-plugin#30]
## Description
We need to ensure the UI compatibility with the next version of OpenSearch's security-dashboards-plugin v2.11.0.
This update is still being discussed, but we need to be aware of potential issues.

For that, we need to:

- [x] Review OpenSearch's security-dashboards-plugin latest stable changelog. 
- [x] Identify improvements and potential impact on the UI.
- [x] Create new tracking and development branches.
- [x] Develop a testing environment to verify our components would work under this new build.

## Issues
-  _List here the detected issues_

**Comment by yenienserrano** [comment]
wz-4.9 branch was created with the changes waiting for 4.9.0

**Comment by AlexRuiz7** [comment]
### opensearch-security-dashboards-plugin 2.11.0.0 release notes

https://github.com/opensearch-project/security-dashboards-plugin/blob/main/release-notes/opensearch-security-dashboards-plugin.release-notes-2.11.0.0.md

Nothing risky for our fork
