### ISSUE TITLE
Support new Wazuh version 5.0.0 in `wazuh-security-dashboards-plugin` repository

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-security-dashboards-plugin#37]
## Description

This issue attempts to support a new version 5.0.0 in the `wazuh-security-dashboards-plugin` repository

## Tasks

- [x] Create numbered branch for current `master` version (`4.9.0`) using `master` branch on `wazuh-security-dashboards-plugin` repository.
- [x] Bump `master` branch to `5.0.0` on `wazuh-security-dashboards-plugin` repository, including revision and changelog.

**Comment by Tostti** [comment]
The required branches were successfully created. There are no references to the Wazuh Version in the code, so there are no changes to do in the bump process.

**Comment by asteriscos** [comment]
LGTM :heavy_check_mark:
