### ISSUE TITLE
Scheduled upward merges for numbered branches in wazuh-security-dashboards-plugin repository - Fortnight #11

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-security-dashboards-plugin#61]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.8.1-into-4.9.0`.

### 4.8.1
- [ ] Update changelog.
- [ ] Merge branch `4.8.1` into branch `4.9.0`.

**Comment by rauldpm** [comment]
Repository created in 4.9.0, no action needed
